In [ ]:
import numpy as np

# Q.1 create a numpy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:

arr=np.array([0,1,2,3,4,5])
print(arr.dtype)



int64


# Q.2 Given a numpy array 'arr' ,check if its data type is float64

In [ ]:

arr=np.array([1.5,2.6,3.9])
if arr.dtype==np.float64:
  print(True)
else:
  print(False)


True


# Q.3 create a numpy array 'arr' with a data type of complex128 containing three complex numbers

In [ ]:

arr=np.array([2+3j,8+8j,5+8j],dtype=np.complex128)
arr

array([2.+3.j, 8.+8.j, 5.+8.j])

# Q.4 Convert  an existing numpy array 'arr' of integers to float32 data type

In [ ]:
arr=np.array([1,7,8,4])
arr1=np.float32(arr)
arr1

array([1., 7., 8., 4.], dtype=float32)

# Q.5 Given a numpy array 'arr' with float64 datatype, covert it to float32 to reduce decimal precision

In [ ]:
arr=np.array([2.556789001,7.983452005,3.686789003],dtype=np.float64)
arr1=np.float32(arr)
arr1

array([2.556789, 7.983452, 3.686789], dtype=float32)

# Q.6 write a function array_attributes that takes a numpy array as input and return its shape,size,and data type

In [ ]:
def array_attributes(a):

  print('the shape of  array is ',a.shape)
  print('the size of  array is ',a.size)
  print('the type of  array is  ',a.dtype)

result=np.array([1,2,3,4])
array_attributes(result)

the shape of  array is  (4,)
the size of  array is  4
the type of  array is   int64


# Q.7 create a function array_dimension that takes a numpy array as input and return its dimensionally


In [ ]:
def array_dimension(a):

  return a.ndim
result=np.array([[1,2,3,4,5],
                [7,8,9,0,8]])
array_dimension(result)
print(result)
print('the dimension of this array is',array_dimension(result))

[[1 2 3 4 5]
 [7 8 9 0 8]]
the dimension of this array is 2


# Q.8 design a function item_size_info that takes a numpy array as input and returns the item size and the total sizes in bytes

In [ ]:
def item_size_info(a):
  print('the item size is',a.itemsize)#item size>> memory occupied by each element of array
  print('the total sizes in bytes',a.size*a.itemsize)# total sizes>> memory in bytes occupied by all the elements of array
result=np.array([9,7,87,65])
item_size_info(result)

the item size is 8
the total sizes in bytes 32


# Q.9 create a function array_strides that take numpy array as input and returns the strides of the array

In [ ]:
#stride represents how many bytes we have to skip to get to the next element of that dimension
def array_strides(b):

  return b.strides
result=np.array([[1,2,3],[9,0,8]])

array_strides(result)

2


(24, 8)

# Q.10 Design a function shape_stride_relationship that takes a numpy array as input and returns the shape and strides of the array


In [ ]:
def shape_stride_relationship(n):
  print('the shape of given array is',n.shape)
  print('the strides of the array is',n.strides)
result=np.array([[1,5,6],
                [8,9,0],
                [5,4,3]])
shape_stride_relationship(result)

the shape of given array is (3, 3)
the strides of the array is (24, 8)


# Q.11  Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.


In [ ]:
def create_zeros_array(n):
  p=int(n)
  return np.zeros(p)
answer=4
create_zeros_array(answer)


array([0., 0., 0., 0.])

# Q.12 Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`


In [ ]:
def create_ones_matrix(rows,cols):
  return np.ones((rows,cols))
row=3
col=2
print(create_ones_matrix(row,col))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


# Q.13  Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.


In [ ]:
def generate_range_array(start,stop,step):
  return np.arange(start,stop,step)
Start=7
Stop=100
Step=10
print(generate_range_array(Start,Stop,Step))

[ 7 17 27 37 47 57 67 77 87 97]


# Q.14 . Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).



In [ ]:
def generate_linear_space(start,stop,num):
  a=float(start)
  b=float(stop)
  c=int(num)
  return np.linspace(a,b,c)
p=12.6
q=89.9
r=15
generate_linear_space(p,q,r)

array([12.6       , 18.12142857, 23.64285714, 29.16428571, 34.68571429,
       40.20714286, 45.72857143, 51.25      , 56.77142857, 62.29285714,
       67.81428571, 73.33571429, 78.85714286, 84.37857143, 89.9       ])

# Q.15 Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.


In [ ]:
def create_identity_matrix(n):
  return np.eye(n)
num=3
create_identity_matrix(num)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Q.16  Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
def convert_to_array(l):
  return np.array(l)
l=[1,2,3,4,5]
convert_to_array(l)

array([1, 2, 3, 4, 5])

# Q.17 Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.


In [ ]:
arr=np.array([1,5,6,7])
arr1=arr.view()
arr1

array([1, 5, 6, 7])

# Q.18  Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
def concatenates(arr1,arr2):
  return np.stack((array1,array2),axis=0)
array1=np.array([[9,0,8],[2,4,8]])
array2=np.array([[4,3,2],[9,8,7]])
concatenates(array1,array2)


array([[[9, 0, 8],
        [2, 4, 8]],

       [[4, 3, 2],
        [9, 8, 7]]])

# Q.19 Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.



In [ ]:
arr1=np.array([[1,2,3],
              [9,0,8]])
arr2=np.array([[1,7,8]])
np.concatenate((arr1,arr2),axis=0)

array([[1, 2, 3],
       [9, 0, 8],
       [1, 7, 8]])

# Q.20 . Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
def vertically_stack(t):
  return np.vstack(t)#for vertically stack
arr1=np.array([[1,5,6,7],
              [9,0,8,7]])
arr2=np.array([[6,50,0,7],
              [5,0,8,1]])
arr3=np.array([[2,5,4,7],
              [3,0,7,7]])
vertically_stack([arr1,arr2,arr3])#multiple array given as a list

array([[ 1,  5,  6,  7],
       [ 9,  0,  8,  7],
       [ 6, 50,  0,  7],
       [ 5,  0,  8,  1],
       [ 2,  5,  4,  7],
       [ 3,  0,  7,  7]])

# Q.21 Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.


In [ ]:
def create(start,stop,num):
  a=int(start)
  b=int(stop)
  c=int(num)
  return np.arange(a,b+1,c)
p=12
q=87
r=5
create(p,q,r)

array([12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87])

# Q.22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).


In [ ]:
def equally_spaced():
  return np.linspace(0,1,10)
equally_spaced()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Q.23 Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


In [ ]:
def log_space():
  return np.logspace(1,1000)
log_space()


/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 2.44205309e+021, 5.96362332e+041, 1.45634848e+062,
       3.55648031e+082, 8.68511374e+102, 2.12095089e+123, 5.17947468e+143,
       1.26485522e+164, 3.08884360e+184, 7.54312006e+204, 1.84206997e+225,
       4.49843267e+245, 1.09854114e+266, 2.68269580e+286, 6.55128557e+306,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf])

# Q.24 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.


In [ ]:
import pandas as pd
arr=np.random.randint(1,100,(5,3))
pd.DataFrame(arr)



0   1   2
0  53  26  15
1  78  17  15
2  25  48  97
3  87  57  49
4  44   3  27

# Q.25 Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.


In [ ]:
def pandas_dataframe(df,column_name):
  df[column_name]=np.where(df[column_name]<0,0,df[column_name])
  return df
data=pd.DataFrame({'a':[1,-8,-9],
                   'b':[-2,7,8],
                   'C':[8,5,-1]}
)
pandas_dataframe(data,'a')

a  b  C
0  1 -2  8
1  0  7  5
2  0  8 -1

# Q.26 Access the 3rd element from the given Numpy array
  arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr=np.array([10,20,30,40,50])
arr[2]

30

# Q.27 Retrieve the element at index (1, 2) from the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d = np.array([[1, 2,3],[4, 5, 6],[7, 8, 9]])
arr_2d[1][2]

6

# Q.28  Using boolean indexing, extract elements greater than 5 from the given numpy array
arr=np.array([3, 8, 2, 10, 5, 7])

In [ ]:
arr=np.array([3, 8, 2, 10, 5, 7])
p=arr>5#boolean indexing
r=arr[p]
r

array([ 8, 10,  7])

# Q.29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

# Q.30  Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d = np.array([[1, 2, 3],[4,5,6],[7, 8, 9]])
result=arr_2d[:2,1:3]
result


array([[2, 3],
       [5, 6]])

# Q.31 Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array

In [ ]:
arr=np.array([[1,2,3,4],
              [9,7,5,3],
              [1,4,5,6]])
idx=np.array([[0],[1],[2]])
def extract_elements():
  return arr[idx,idx]
extract_elements()



array([[1],
       [7],
       [5]])

# Q.32 Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.


In [ ]:
arr=np.array([3, 8, 2, 10, 5, 7])
def filter_elements(threshold):
  p=arr>threshold
  r=arr[p]
  print(p)
  return r
filter_elements(9)

[False False False  True False False]


array([10])

# Q.33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [ ]:
def extract_element(arr,index1,index2,index3):
  return arr[index1,index2,index3]
arr=np.array([[[2,9],[0,7]],
              [[3,5],[8,1]],
              [[3,0],[4,2]]])
index1=np.array([1,2])
index2=np.array([0,1])
index3=np.array([1,0])
extract_element(arr,index1,index2,index3)

array([5, 4])

# Q.34 Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [ ]:

def return_array(arr,condition1,condition2):
  print([condition1 & condition2])#for result in boolean
  print(arr[condition1 & condition2])#for both condition to be satisfied use '&'
cond1=arr>2
cond2=arr<9
arr=np.array([2,3,4,0,9,8])
return_array(arr,cond1,cond2)


[array([False,  True,  True, False, False,  True])]
[3 4 8]


# Q.35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [ ]:
def elements(arr,row,col):
  return arr[row,col]
arr=np.array([[1,2],[5,6]])
row=np.array([0])
col=np.array([1])
elements(arr,row,col)

array([2])

# Q.36 Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
arr=np.array([[1,2,3],
             [4,6,7,],
             [5,0,9]])
arr+5#by using broadcasting


array([[ 6,  7,  8],
       [ 9, 11, 12],
       [10,  5, 14]])

# Q.37 Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting

In [ ]:
arr1=np.array([[1,2,3]])
arr2=np.array([[8,9,0,7],
              [1,2,3,5],
              [0,5,6,7]])
arr2*arr1.T

array([[ 8,  9,  0,  7],
       [ 2,  4,  6, 10],
       [ 0, 15, 18, 21]])

# Q.38 Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [ ]:
arr1=np.array([1,2,3,8])
arr2=np.array([[8,9,0,7],
              [1,2,3,5],
              [0,5,6,7],
               [8,7,6,5]])
a=arr1
arr2+a

array([[ 9, 11,  3, 15],
       [ 2,  4,  6, 13],
       [ 1,  7,  9, 15],
       [ 9,  9,  9, 13]])

# Q.39 Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [ ]:
arr1=np.array([[4],
              [6],
              [7]])
arr2=np.array([1,2,3])
arr1+arr2

array([[ 5,  6,  7],
       [ 7,  8,  9],
       [ 8,  9, 10]])

# Q.40 Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [ ]:
arr1=np.array([[6,7,8],
              [8,9,0]])
arr2=np.array([[1,2],
       [3,4]])

arr1.T*arr2[:,np.newaxis]

array([[[ 6, 16],
        [ 7, 18],
        [ 8,  0]],

       [[18, 32],
        [21, 36],
        [24,  0]]])

# Q.41  Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

# Q.42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=1)#for maximum value in each row

array([3, 6])

# Q.43  For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.argmax(axis=0)#for indices of max values in each column

array([1, 1, 1])

# Q.44 For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4,5,6]])

In [ ]:
arr = np.array([[1, 2, 3],
                [4,5,6]])
def moving_sum():
  return arr.cumsum(axis=1)#for calculating moving sum along rows
moving_sum()



array([[ 1,  3,  6],
       [ 4,  9, 15]])

# Q.45 In  the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])


In [ ]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
np.all(arr%2==0,axis=0)

array([False, False, False])

# Q.46 Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
original_array = np.array([1, 2, 3, 4, 5, 6])
m=int(input('Enter number of rows:'))
n=int(input('Enter number of columns:'))
if m*n==original_array.size:
  print(np.matrix(original_array.reshape(m,n)))
else:
  print('cannot reshaped')


Enter number of rows:3
Enter number of columns:2
[[1 2]
 [3 4]
 [5 6]]


# Q.47 Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
a=lambda input_matrix:input_matrix.flatten()#function to flatten the given matrix
a(input_matrix)

array([1, 2, 3, 4, 5, 6])

# Q.48 Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
np.concatenate((array1,array2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Q.49  Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                          [7, 8, 9]])
new_array=np.array_split(original_array,6,axis=1)#for splitting array into many subarrays along a specified axis
new_array

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]]),
 array([], shape=(3, 0), dtype=int64),
 array([], shape=(3, 0), dtype=int64),
 array([], shape=(3, 0), dtype=int64)]

# Q.50 Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1,3]

In [ ]:
def elements(a,b,c,d):
  p=3
  while p>0:
    for i,j in zip(b,c):
      w=np.insert(a,b,c)
      p=p-1
  return np.delete(w,d)
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1,3]
elements(original_array,indices_to_insert,values_to_insert,indices_to_delete)


array([ 1, 10,  4, 11,  5])

# Q.51 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))
arr1+arr2

array([[ 2,  6,  5],
       [14,  9, 13],
       [ 9, 10,  2]])

# Q.52 Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
arr1=np.arange(10,0,-1)
arr2=np.arange(1,11)
arr1-arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

# Q.53 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
arr1=np.random.randint(1,5,(2,2))
arr2=np.random.randint(1,5,(2,2))
arr1*arr2

array([[3, 6],
       [6, 3]])

# Q.54 Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)

arr1/arr2

array([2., 2., 2., 2., 2.])

# Q.55  Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
arr1=np.arange(1,6)
arr2=np.arange(5,0,-1)
arr1**arr2


[1 2 3 4 5]
[5 4 3 2 1]


array([ 1, 16, 27, 16,  5])

# Q.56  Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
def occurences(arr,substring):
  p=np.char.count(arr,substring)#to count the occurences of specific substring within a numpy array of strings
  return p

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
occurences(arr,'m')


array([0, 0, 0, 1, 0])

# Q.57 Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
def uppercase_characters(arr):
  uppercase=[]
  for i in arr:
    for s in i:
      if s.isupper():
        uppercase.append(s)
  return uppercase

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters(arr)



['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

# Q.58 Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [ ]:
def replaces(arr,substring,replace_with):
  return np.array([s.replace(substring,replace_with) for s in arr])

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

replaces(arr,'a','e')

array(['epple', 'benene', 'grepe', 'pineepple'], dtype='<U9')

# Q.59 Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [ ]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def concatenates_strings(a,b):
    return np.char.add(arr1,arr2)

concatenates_strings(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

# Q.60 Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
def find_length(arr):
  longest_length=max(len(word) for word in arr)
  return longest_length
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
find_length(['apple', 'banana', 'grape', 'pineapple'])

9

# Q.61  Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [ ]:

arr=np.random.randint(1,1000,(10,10))
print(arr.mean())
print(np.median(arr))
print(arr.var())
print(arr.std())

488.55
521.5
79889.3675
282.64707233580185


# Q.62  Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the datasets.

In [ ]:
arr=np.random.randint(1,100,(10,5))
print(np.percentile(arr,25))
print(np.percentile(arr,75))

32.25
75.5


# Q.63 Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [ ]:
arr1=np.array([[1,2],[9,8]])
arr2=np.array([[3,4],[8,6]])

np.corrcoef(arr1,arr2)[0,1]



-0.9999999999999999

# Q.64 Create two matrices and perform matrix multiplication using NumPy's `dot` function.


In [ ]:
arr1=np.array([[0,1],
              [9,8]])
arr2=np.array([[0,1,8],
              [9,8,4]])
np.dot(arr1,arr2)

array([[  9,   8,   4],
       [ 72,  73, 104]])

# Q.65 Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [ ]:
arr=np.random.randint(10,1000,(2,25))
print('10th percentile:',np.percentile(arr,10))
print('50th(median) percentile:',np.percentile(arr,50))
print('90th percentile:',np.percentile(arr,90))
print('first quartile:',np.percentile(arr,25))
print('third quartile:',np.percentile(arr,75))

10th percentile: 96.80000000000001
50th(median) percentile: 588.0
90th percentile: 927.3
first quartile: 240.0
third quartile: 769.0


# Q.66 Create a NumPy array of integers and find the index of a specific element.


In [ ]:
arr1=np.array([0,6,8,3])
element=8
np.where(arr1==element)

(array([2]),)

# Q.67 Generate a random NumPy array and sort it in ascending order.


In [ ]:
arr=np.random.randint(1,10,(1,10))
np.sort(arr)

array([[3, 4, 7, 7, 7, 8, 8, 8, 9, 9]])

# Q.68 Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])


In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])
np.extract(arr>20,arr)

array([25, 42, 30])

# Q.69 Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])



In [ ]:
arr = np.array([1, 5, 8, 12, 15])
np.extract(arr%3==0,arr)

array([12, 15])

# Q.70 Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])



In [ ]:
arr= np.array([10, 20, 30, 40, 50])
modified=[]
for i in arr:
  if i>=20 and i<=40:
    modified.append(i)
print(np.array(modified))


[20 30 40]


# Q.71 For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])



In [ ]:
import numpy as np
arr = np.array([1, 2, 3])

arr.dtype.byteorder

'='

# Q.72 For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

#  Q.73 For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().
arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
m=arr.newbyteorder()

print('original array :',arr)
print('by swapping byteorder we get array:',m)

original array : [1 2 3]
by swapping byteorder we get array: [16777216 33554432 50331648]


# Q.74 For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().
arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder in ('='):
  print(arr.newbyteorder())
elif arr.dtype.byteorder in ('<'):
  print(arr.newbyteorder())

elif arr.dtype.byteorder('>'):
  print(arr.newbyteorder())

else:
  print()


[16777216 33554432 50331648]


# Q.75 For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder in '>':
  print('current system is more endianess,so byte swapping is necessary')
elif arr.dtype.byteorder in '<':
  print('current system is less endianness,so byte swapping is necessary')
elif arr.dtype.byteorder in '=':
  print('no need of byteswapping')
else:
  print()

no need of byteswapping


# Q.76 Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`

In [ ]:
arr1=np.arange(1,11)
copy_arr=arr1.copy()
print('its copy of original array:',copy_arr)
copy_arr[1]=9090908
print('after modifying an element in copy, copy_arr :',copy_arr)
print('after modifying its copy, original array will become:',arr1)
print('copy_arr does not affect arr1')


its copy of original array: [ 1  2  3  4  5  6  7  8  9 10]
after modifying an element in copy, copy_arr : [      1 9090908       3       4       5       6       7       8       9
      10]
after modifying its copy, original array will become: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr does not affect arr1


# Q.77 Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [ ]:
matrix=np.random.randint(20,100,(3,3))
print('original array before modification:',matrix)
view_slice=matrix[:2,1:2]
print('a slice from original array:',view_slice)
view_slice[1,0]=45004
print('a slice after mdifying a element',view_slice)
print('original array after modification ',matrix)
print('it changes the original matrix')



original array before modification: [[74 95 38]
 [92 58 54]
 [55 83 88]]
a slice from original array: [[95]
 [58]]
a slice after mdifying a element [[   95]
 [45004]]
original array after modification  [[   74    95    38]
 [   92 45004    54]
 [   55    83    88]]
it changes the original matrix


# Q.78 Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [ ]:
r=np.arange(1,13)
array_a=r.reshape(4,3)
view_b=array_a[:2,:2]
print('broadcasted array is:',view_b+5)
print('original array:',array_a)


broadcasted array is: [[ 6  7]
 [ 9 10]]
original array: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2]
 [4 5]]


# Q.79  Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array

In [ ]:
orig_array=np.arange(1,9).reshape(2,4)
print('orig_array of shape (2,4):',orig_array)
reshaped_view=orig_array.reshape(4,2)
print('reshaped_view is:',reshaped_view)
reshaped_view[0,0]=12

print('after modify an element in reshaped_view , the orig_array is:',orig_array)
print('yes, it reflects changes in original orig_array')

orig_array of shape (2,4): [[1 2 3 4]
 [5 6 7 8]]
reshaped_view is: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
after modify an element in reshaped_view , the orig_array is: [[12  2  3  4]
 [ 5  6  7  8]]
yes, it reflects changes in original orig_array


# Q.80 Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


In [ ]:
data=np.random.randint(2,100,(3,4))


datacopy=np.extract(data>5,data)
data_copy=datacopy.reshape(3,4)
print('data_copy of elements greater than 5 is:',np.array(data_copy))
data_copy[1,2]=1000
print('after modify an element in data_copy, data_copy is:',data_copy)
print('after modification original data is:',data)
print('it does not affects the original data')


data_copy of elements greater than 5 is: [[39 74  9 47]
 [45 63 71 95]
 [10 85 76 49]]
after modify an element in data_copy, data_copy is: [[  39   74    9   47]
 [  45   63 1000   95]
 [  10   85   76   49]]
after modification original data is: [[39 74  9 47]
 [45 63 71 95]
 [10 85 76 49]]
it does not affects the original data


# Q.81 Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [ ]:
mat1=np.matrix([1,7])
mat2=np.matrix([6,10])
print('addition of both matrices :',mat1+mat2)
print('subtraction of both matrices:',mat1-mat2)

addition of both matrices : [[ 7 17]]
subtraction of both matrices: [[-5 -3]]


# Q.82  Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [ ]:
c=np.matrix([[1,2],
            [6,7],
            [9,4]])
d=np.matrix([[2,9,0,8],
            [8,7,6,3]])
c@d#matrix multiplication

matrix([[ 18,  23,  12,  14],
        [ 68, 103,  42,  69],
        [ 50, 109,  24,  84]])

# Q.83 Create a matrix `E` and find its transpose.

In [ ]:
E=np.matrix([[2,9,0,8],
            [8,7,6,3]])
print('transpose of given matrix is:',E.T)#transpose

transpose of given matrix is: [[2 8]
 [9 7]
 [0 6]
 [8 3]]


# Q.84 Generate a square matrix `F` and compute its determinant.


In [ ]:
F=np.matrix([[1,2],
            [6,7]])
print('determinant of given square matrix is:',int(np.linalg.det(F)))

determinant of given square matrix is: -5


# Q.85 Create a square matrix `G` and find its inverse.


In [ ]:
G=np.matrix([[1,2],
            [6,7]])
print('inverse of given matrix is:',np.linalg.inv(G))

inverse of given matrix is: [[-1.4  0.4]
 [ 1.2 -0.2]]
